language: java

sudo: false

jdk:
#  - openjdk7
#  - oraclejdk7
  - oraclejdk8

script: mvn clean verify -f hikari-dbm/pom.xml

# safelist
branches:
  only:
  - master
  - stable

after_success:
  - bash <(curl -s https://codecov.io/bash)